### ISSUE TITLE
Installation reboots when "About 2 Minutes Remaining"

### ISSUE THREAD

**Issue by emrebarutcu** [khanhtran-cse/lenovo-ideapad-l340-hackintosh#10]
I use your efi file and I successfully had the first boot. Then with disk utility I formatted my hard drive in APFS. Then started to install but when the bar is about 75% and it says "About 2 Minutes Remaining", some white text on black bacground appears and system reboots. After reboot "Boot to MacOS" option appears. I mean it shows that it is installed. But when I tried to boot it, after verbose logs, apple logo appears with progress bar under, after waiting to bar get fulled, text says "Less than a minute" and reboots again. 

If I try to boot my flash drive, it has panic. I tried to remove ACPI patches but nothing changed.

**Comment by khanhtran-cse** [comment]
Do you use Samsung PM981 SSD? MacOS doesn't support this disk.

**Comment by emrebarutcu** [comment]
I use it for windows. I have 1 TB HDD. I use HDD to install MacOS. HDD's brand is "HGST".

**Comment by khanhtran-cse** [comment]
I don't use this SSD so I don't know how to fix it. You can search about install Macos on PM981 or how to disable SSD.

**Comment by emrebarutcu** [comment]
Solved by using custom efi folder.
[CLOVER.zip](https://github.com/khanhtran-cse/lenovo-ideapad-l340-hackintosh/files/4776889/CLOVER.zip)
