### ISSUE TITLE
Questions about Apple id, iCloud

### ISSUE THREAD

**Issue by seromy** [khanhtran-cse/lenovo-ideapad-l340-hackintosh#12]
I have tried your EFI and it works great, but I was wondering if those features can use or not
- Sign in to Apple id
- Sign in to iCloud
- Using iMessage and FaceTime (I have already tried and it not work)

If anyone knows, please share your experience🙏

**Comment by khanhtrancse** [comment]
Hi @itztaylorau 

If you just created a new Apple account, you must sign in on a real mac (or iphone) firstly to active account. Then you can sign in to hackintosh. I think you also can try change Serial number to correct Serial number and sign in again if you didn't have real mac (or iphone).

For iMessage and iFace, you can search how to enable iFace and iMessage on hackintosh. I don't  use it so it don't care how to fix it.
