### ISSUE TITLE
Brightenss cntrol and slider not working

### ISSUE THREAD

**Issue by ghanshyamvanol** [khanhtran-cse/lenovo-ideapad-l340-hackintosh#16]
My graphics card 630 was showing with 1.5gb but in down no brightenss control any idea plz tell and battery life are so weak

**Comment by ghanshyamvanol** [comment]
I am lazy not research  anything now i research everything  and I don't know its patched manually now its fixed

**Comment by vicebtx** [comment]
Hi @ghanshyamvanol  can You share the steps you followed to fix the brightness control keys?
