### ISSUE TITLE
Possible continuation of the project

### ISSUE THREAD

**Issue by Kitsunejasutin** [khanhtran-cse/lenovo-ideapad-l340-hackintosh#36]
I'm sad to know that this project has already ended, is there any people who's continuing this project on the same laptop? Gladly to know if there's any. Thanks!

**Comment by seromy** [comment]
I am using this repo files and modified some of the files. I am currently on Mac OS 12.0.1 with Open Core 0.7.5 .

**Comment by Kitsunejasutin** [comment]
@itztaylorau it is monterey right? Did you released your efi for it?

**Comment by seromy** [comment]
Yes it is Monterey, and I am considering releasing it before this Christmas.

**Comment by Kitsunejasutin** [comment]
@itztaylorau oh it's nice to hear that, looking forward to it. Thanks

**Comment by Kitsunejasutin** [comment]
@itztaylorau if you don't mind, is the efi ready?

**Comment by Debjit0** [comment]
eagerly waiting for your update on montery..!

**Comment by Kitsunejasutin** [comment]
> eagerly waiting for your update on montery..!

Somehow I successfully created a efi for bigsur without problem reading some tutorials that Bluetooth might not work on Monterey so I didn't try yet.

**Comment by Debjit0** [comment]
> > eagerly waiting for your update on montery..!
> 
> Somehow I successfully created a efi for bigsur without problem reading some tutorials that Bluetooth might not work on Monterey so I didn't try yet. 

Can u please share efi of Big Sur?

**Comment by Kitsunejasutin** [comment]
> > > eagerly waiting for your update on montery..!
> > 
> > 
> > Somehow I successfully created a efi for bigsur without problem reading some tutorials that Bluetooth might not work on Monterey so I didn't try yet.
> 
> Can u please share efi of Big Sur?

You can check my github it's pinned

**Comment by Debjit0** [comment]
> > > > eagerly waiting for your update on montery..!
> > > 
> > > 
> > > Somehow I successfully created a efi for bigsur without problem reading some tutorials that Bluetooth might not work on Monterey so I didn't try yet.
> > 
> > 
> > Can u please share efi of Big Sur?
> 
> You can check my github it's pinned

tysmmm.. ill install tonight

**Comment by seromy** [comment]
> eagerly waiting for your update on Monterey..!

I am sorry for the late release, here is the forked and edited latest Monterey version.
Please refer to itztaylorau/lenovo-ideapad-l340-hackintosh (located in my profile top)

**Comment by Debjit0** [comment]
> > eagerly waiting for your update on Monterey..!
> 
> I am sorry for the late release, here is the forked and edited latest Monterey version.
> Please refer to itztaylorau/lenovo-ideapad-l340-hackintosh (located in my profile top)

Thank you so much for your hardwork. But there's an issue. When I start installing bigsur,the installer works fine. But it gets stuck at "12 mins remaining" and then apple boot loop occurs.
Can u please help
