### ISSUE TITLE
Request for a simple installation guide

### ISSUE THREAD

**Issue by seromy** [khanhtran-cse/lenovo-ideapad-l340-hackintosh#5]
I have tried to follow many articles on the Internet but still can't install it. It will be awesome if the developer add a simple installation guide for reference.

**Comment by khanhtrancse** [comment]
Hi @itztaylorau 
Simple installation is copy EFI folder to your EFI partition.

But keep in mind, hackintosh has no simple installation. You must try and error to fix some issues.

**Comment by seromy** [comment]
Hi there, sorry for bothering you. 
Could you tell us which system image do you use?
I have tried to use my own but with no luck.

**Comment by khanhtrancse** [comment]
Hi @itztaylorau 
Does your laptop have 8gb RAM? Does you change **SMBIOS>Memory>Modules>Size** in config.plist file to **8196**?

**Comment by seromy** [comment]
Yes, my laptop only have 8 GB ram and I change to 8196 already.

**Comment by khanhtrancse** [comment]
Did you try to remove DSDT.aml and SSDT-9-CB-01.aml in EFI/CLOVER/ACPI/patched?

**Comment by seromy** [comment]
Yes I tried but still no luck😭

**Comment by khanhtrancse** [comment]
Can you provide more info? Screenshot or something

**Comment by seromy** [comment]
Here are my screenshot of the error I got. The photo quality may be low since it is difficult to capture those moving text.
https://drive.google.com/drive/folders/1-SZie3qbWKdgiQQPAi0mm6ETEzgo05It?usp=sharing

**Comment by khanhtran-cse** [comment]
If your hack reboot at booting, you can choose **Don't reboot at panic** in clover. Then take a screenshot again.

To choose **Don't reboot at panic**: At clover Menu -> Press Space -> This will show you this options

**Comment by seromy** [comment]
![IMG_20200514_115407](https://user-images.githubusercontent.com/43441144/81890985-ddcf1780-95d9-11ea-9649-41eaefbdec1f.jpg)
 
I got the following result.

**Comment by khanhtran-cse** [comment]
Can you attach EFI folder?

**Comment by seromy** [comment]
[EFI.zip](https://github.com/khanhtran-cse/lenovo-ideapad-l340-hackintosh/files/4625979/EFI.zip)
Sure and here is my EFI folder.

**Comment by khanhtran-cse** [comment]
[EFI 2.zip](https://github.com/khanhtran-cse/lenovo-ideapad-l340-hackintosh/files/4626001/EFI.2.zip)
Please test this config.

**Comment by itztaylorau** [comment]
Unfortunately it's not work for me😅.

**Comment by khanhtran-cse** [comment]
What's your screenshot?

**Comment by seromy** [comment]
Unfortunately, it does not work for me 😢 . I stuck at this page for almost 7 minutes.
I selected the following option:
-v
nv_disable=1
do not reboot on panic
disable power nap (default selection)

![Webp net-compress-image](https://user-images.githubusercontent.com/43441144/81892855-b4fd5100-95de-11ea-8e54-20c9b03e9f3c.jpg)

**Comment by seromy** [comment]
Also, there is no progress bar when I boot it normally.

**Comment by khanhtran-cse** [comment]
How did you create installer?

**Comment by seromy** [comment]
I use balenaEtcher to create the USB.

**Comment by khanhtran-cse** [comment]
wtf?

**Comment by seromy** [comment]
I'm sorry but is there anything I did wrong during the installation process?

**Comment by khanhtran-cse** [comment]
Do you have access to macos? You can run macos on virtualbox if you don't have real mac.

On macos, you can follow the guide to create installer:
https://support.apple.com/en-us/HT201372

You cannot create installer from window or linux.

**Comment by seromy** [comment]
Okay, I will try it now.

**Comment by seromy** [comment]
Thanks so much! I install it successfully yesterday.
