### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by ivan-holeshau** [khanhtran-cse/lenovo-ideapad-l340-hackintosh#6]
Hey. I have the same laptop as yours (lenovo l340 gaming 15 irh). Thank you very much for your work with clover.
I have a very quiet sound, I installed Boom 2 and the driver. The laptop stopped loading and I put katalin on top and in the end, Boom 2 started working well and I raised the sound volume 3-4 times somewhere. Maybe it will help you.

**Comment by khanhtrancse** [comment]
Thanks you @ivan-holeshau,

I will try your method. If it works, I will update readme to help other people.
