### ISSUE TITLE
Using with i5-9300HF

### ISSUE THREAD

**Issue by tuandqx9hd** [khanhtran-cse/lenovo-ideapad-l340-hackintosh#9]
I have same laptop, but chipset is i5-9300HF. I used your EFI but I can not get the UHD 630 working in Catalina. I tried to fix but it only show with 8MB. And my touchpad is ELAN0626 also doesn't work. Can you help me fix that? Thank you.

![Screen Shot 2020-05-30 at 09 14 43](https://user-images.githubusercontent.com/66175638/83333566-026ff400-a256-11ea-8565-889a956513bb.png)

**Comment by khanhtrancse** [comment]
You can try voodooi2c + voodooi2cHid for your trackpad. If it doesn't work, try voodooi2c + voodooelan. For more detail, visit here https://voodooi2c.github.io/#Satellite%20Kexts/Satellite%20Kexts

**Comment by rbolanoherrera** [comment]
Hi. can you share the steps you do for the Ideapad i5-9300H.

Thanks!

**Comment by albasyir** [comment]
Up

**Comment by tuandqx9hd** [comment]
Download Catalina in App Store then create USB boot following https://support.apple.com/en-qa/HT201372. After create boot usb, use clover configurator mount usb efi partition then put guide efi into this

**Comment by rbolanoherrera** [comment]
Thanks!

**Comment by aryayudha** [comment]
Hi @micheal9ci how about your grapichs? it's solve?

**Comment by rbolanoherrera** [comment]
> Download Catalina in App Store then create USB boot following https://support.apple.com/en-qa/HT201372. After create boot usb, use clover configurator mount usb efi partition then put guide efi into this

Can you share, boot clover options?
